sudo: false
language: node_js
node_js:
- '6'
env:
  global:
    secure: cXSfe/DZUMsomv3I7AaO6HItVo4QwdaHv/dPzObjeP1V07r+ULhNo/lb8YgXLo1ryBu9nflXazpCjZ2Ef3S+F+7PUzK2xhP9z56RnDDnwcbdFlMuJ3LKN2GKHEvebQQInFqnwkgFI4bSQLHgyUPiZs5mj1fss4UWeKvFoqDJdHk=
before_script: npm install -g grunt-cli
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
