sudo: false
language: node_js
node_js:
- '6'
env:
  global:
    secure: JGUjM3LP3i+DLPZ+jAFYItukR+5D3vr2Y+O87ZcGH2ZVRQrR5PtTLp9clHJd0a3xbA9a7xkUbQ6n4SZ3NxKdx5pRwqSyFRZRAExmaY4rxpdHfsmGpIKYDpyhbgqg9f9yleNbOYgD4CwcFqccJknYOJxocAbIIxwpYh3VHWZw5pw=
before_script: npm install -g grunt-cli
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
