source 'https://rubygems.org'

gemspec
gem 'rake', '10.0.1'
gem 'middleman'

group :development do
  gem 'rdoc'
  gem 'yard'
end

group :test do
  gem 'cucumber', '1.3.20'
  gem 'aruba'
  gem 'rspec'
end